### PR TITLE
added the InfiniteStopConvexPoly struct to support convex poly aperture

### PR DESCRIPTION
**Pull request by galran**
added the RectJitterGrid to the Emitters.Origins to support better (less clamping) way of sampling
added a convex polygon Stop shape to support the hexagon shaped lenses

### CODE REVIEW

**Comment by friggog** [comment]
Shouldn’t this check for intersection with the poly as well and return empty if intersection and the plane intersection interval otherwise?

**Comment by friggog** [comment]
Emitter change also seems unrelated to this PR

**Comment by galran** [comment]
> Shouldn’t this check for intersection with the poly as well and return empty if intersection and the plane intersection interval otherwise?

agreed. the code seems weird - will check and maybe split this PR into two

**Review by BrianGun — APPROVED** [review]

**Comment by friggog** [comment]
Replaced by #328

**Pull request closed without merging**
