### PR TITLE
added the InfiniteStopConvexPoly shape to allow aperture for hex lenses.

### PR DESCRIPTION
**Pull request by galran**
also fixed a small bug in convex polygon assert statement.

### CODE REVIEW

**Review by friggog — APPROVED** [review]
Maybe should an allocation test for the new stop just to make sure?

**Comment by galran** [comment]
> 

do i need to add an allocation test explicitly? i thought that they run for all the benchmarks.

**Comment by brian-guenter** [comment]
> > 
> 
> do i need to add an allocation test explicitly? i thought that they run for all the benchmarks.

@galran if you add a new type you need to add an allocation test. Check out test/Benchmarks/Benchmarks.jl. You add your test code to list of tests to perform and then it will be run. This is something we shouldn't skip - if we let allocations creep in it will be difficult to figure out where performance hits are coming from later on.

**Comment by galran** [comment]
added allocation tests. hope i did it correctly.

**Review by brian-guenter — APPROVED** [review]

**Comment by brian-guenter** [comment]
> added allocation tests. hope i did it correctly.

I looked them over. They look correct. And they all passed!

**Review by brian-guenter — APPROVED** [review]

**Review by brian-guenter — APPROVED** [review]

**Review by BrianGun — APPROVED** [review]

**Pull request merged**
