### PR TITLE
Example for deterministic raytracing

### LINKED ISSUE #110: Add example showing new pseudo-sequential ray tracing usage
@cdhf you mentioned that you created a system with a few prisms to exercise the new sequential tracing code. Would you be willing to write that up as an example and add it to the examples documentation? It would help other people understand how to use the feature.

The documentation for examples is located in OpticSim/docs/src/examples.md. The other examples will serve as a template to get everything displaying correcting.

### PR DESCRIPTION
**Pull request by cdhf**
Fixes #110.

### CODE REVIEW

**Comment by BrianGun** [comment]
@cdhf thank you for this example.

**Comment by BrianGun** [comment]
@alfredclwong  doc preview cleanup is failing and maybe preventing this from being merged into main. Or something else it because it didn't get merged. 

Could you take a look at this?

**Comment by alfredclwong** [comment]
It looks like the auto merge was cancelled because you closed the PR before it had a chance to merge (the doc build hasn't finished yet). You should just leave the PR to resolve itself once auto merge is set up.

Doc Preview Cleanup (and any other non-required checks) will not block merging.

**Review by alfredclwong — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
