### PR TITLE
OpenGL fails on Windows tests

### LINKED ISSUE #72: Windows tests failing
OpenGL issue again. Compare the two runs below.

https://github.com/microsoft/OpticSim.jl/runs/2216612484 (previous test pass)
https://github.com/microsoft/OpticSim.jl/runs/2244913138 (empty commit)

OS and venv are identical, Mesa package should be unchanged. Not sure where the error is coming from.

### PR DESCRIPTION
**Pull request by BrianGun**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #72

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration(s)**:

* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by alfredclwong** [comment]
If we are going to skip the tests, can we do it in a way that still allows them all to run on a normal Windows machine?

For example, we could we try using the otestset functionality that was coded into runtests.jl. This would require modifying CI.yml to pass command-line arguments to test. This might not be the easiest solution.

**Comment by galran** [comment]
you should be using Sys.iswindows as a function:

if Sys.iswindows()
...
end

**Comment by BrianGun** [comment]
is there a way to detect that we are running headless? We could make the test a bit more specific that way: if windows and headless  then don't run the tests.

**Comment by alfredclwong** [comment]
On the Github Actions remote machines, an environment variable called CI is set to true, so we can use this as a condition (see 6683d56).

I've also added a patch number bump to this PR.

**Review by galran — APPROVED** [review]

**Pull request merged**
